name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Which branch to checkout and run test"
        required: false
        default: master
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run cy:run 

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: output/e2e/screenshots
